apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-frontend-deployment
  labels:
    app: task-manager-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-manager-frontend
  template:
    metadata:
      labels:
        app: task-manager-frontend
    spec:
      containers:
      - name: task-manager-frontend-container
        image: gcr.io/elite-totality-459909-b4/task-manager-frontend:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-frontend-svc
  labels:
    app: task-manager-frontend
spec:
  type: LoadBalancer
  selector:
    app: task-manager-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 