apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: task-manager
data:
  PORT: "8080"
  NODE_ENV: "production"
  DB_HOST: "127.0.0.1"  # Cloud SQL proxy will be running locally
  DB_NAME: "task_manager"
  PUBSUB_TOPIC: "task-events" 