apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: task-manager
  labels:
    app: frontend
spec:
  type: LoadBalancer # Exposes the frontend externally
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80 # External port
    targetPort: 80 # Container port on Nginx pods 